apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/secret.yaml
  - manifests/configmap.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/statefulset.yaml
  - manifests/todo-backend/service.yaml
  - manifests/todo-backend/deployment.yaml
  - manifests/todo-app/service.yaml
  - manifests/todo-app/deployment.yaml
  - manifests/cronjob.yaml
  - manifests/ingress.yaml
images:
  - name: FRONTEND_IMAGE
    newName: opeyemiorugun/todoapp
    newTag: v4.1.1
  - name: BACKEND_IMAGE
    newName: opeyemiorugun/todoapi
    newTag: v1.1.3